name: Black Code Formatter

#on: [push, pull_request]
#on: [push]
on:
  push:
    branches:
      - master
      - development
    branches-ignore:
      # Push events to branches matching refs/heads/releases/
      - 'releases/**'
    tags-ignore:
      - v* 
  pull_request:
    branches:
      - master

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: Ahuge/black-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLACK_ARGS: "."
